ehs_event_inscription:
    resource: "@EHSBundle/Controller/EventInscriptionController.php"
    type:     annotation
    prefix: /event/

ehs_tag:
    resource: "@EHSBundle/Controller/TagController.php"
    type:     annotation

ehs_appointment:
    resource: "@EHSBundle/Controller/AppointmentController.php"
    type:     annotation

ehs_event:
    resource: "@EHSBundle/Controller/EventController.php"
    type:     annotation

ehs_user:
    resource: "@EHSBundle/Controller/UserController.php"
    type:     annotation

ehs:
    resource: "@EHSBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile