# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
            ROLE_PRESS:       ROLE_USER
            ROLE_ADMIN:       ROLE_PRESS
            ROLE_SUPER_ADMIN: ROLE_ADMIN


    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
                    id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/user/[0-9]+/edit, role: ROLE_USER }
        - { path: ^/user/[0-9]+/, role: ROLE_USER }
        - { path: ^/user/accept, role: ROLE_SUPER_ADMIN }
        - { path: ^/appointment/, role: ROLE_ADMIN }
        - { path: ^/event/[0-9]+/edit, role: ROLE_ADMIN }
        - { path: ^/event/new, role: ROLE_ADMIN }
        - { path: ^/event/registeredList, role: ROLE_ADMIN }
        - { path: ^/event/eventinscription/validated, role: ROLE_ADMIN }
        - { path: ^/event/program/new, role: ROLE_ADMIN }
        - { path: ^/event/program/[0-9]+/edit, role: ROLE_ADMIN }
