<?php

namespace EHSBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventInscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventInscriptionRepository extends EntityRepository
{
}
